pipeline {

  agent none

  environment {
    DOCKER_IMAGE = "thobui2105/my-api"
  }

  stages {
    stage("Build") {
      agent {
        node {label 'master'}
      }
      environment {
        DOCKER_TAG="${GIT_BRANCH.tokenize('/').pop()}-${BUILD_NUMBER}-${GIT_COMMIT.substring(0,7)}"
      }
      steps {
        withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
          sh "echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin"
        }
        sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ./jenkins/api/"
        sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
        
        // clean to save disk
        sh "docker image rm ${DOCKER_IMAGE}:${DOCKER_TAG}"
      }
    }
  }

  post {
    success {
      echo "SUCCESSFULY"
    }
    failure {
      echo "FAILED"
    }
  }

}