{
 "title": "EMQ Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(emqx_client_connected{instance=\"079903ed7615~172.27.0.3\",job=\"079903ed7615\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum(emqx_client_disconnected{instance=\"079903ed7615~172.27.0.3\",job=\"079903ed7615\"})",
     "legendFormat": "disconnected"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_received{instance=\"079903ed7615~172.27.0.3\",job=\"079903ed7615\"}[5m]))",
     "legendFormat": "Messages received"
    },
    {
     "expr": "sum(rate(emqx_messages_sent{instance=\"079903ed7615~172.27.0.3\",job=\"079903ed7615\"}[5m]))",
     "legendFormat": "Messages sent"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emqx_routes_count{instance=\"079903ed7615~172.27.0.3\",job=\"079903ed7615\"}",
     "legendFormat": "Topics"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emqx_subscribers_count{instance=\"079903ed7615~172.27.0.3\",job=\"079903ed7615\"}",
     "legendFormat": "Subscriptions"
    },
    {
     "expr": "emqx_subscriptions_shared_count{instance=\"079903ed7615~172.27.0.3\",job=\"079903ed7615\"}",
     "legendFormat": "Shared Subscriptions"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(emqx_bytes_received{instance=\"pushgateway:9091\",job=\"pushgateway\"}[5m]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum(rate(emqx_bytes_sent{instance=\"079903ed7615~172.27.0.3\",job=\"079903ed7615\"}[5m]))",
     "legendFormat": "Bytes sent"
    }
   ]
  }
 ]
}